feat/ registered-successfully screen
jogamais-ufcg/frontend pull request #65
Opened 2022-12-06 02:56 UTC by magao02

closes #53

2022-12-06 22:46 UTC, kmmelcher requested changes

2022-12-06 22:46 UTC, kmmelcher commented on pages/gerenciar-usuarios/cadastro-sucesso/index.tsx
> +        />
Faltam duas coisas nesse botão:

1. Definir como icon a seta para voltar
2. Definir a função onClick pra voltar a listagem de usuários (ou ao login se essa página não foi definida ainda e add um comentário TODO)

2022-12-06 23:09 UTC, davigsousa commented on pages/gerenciar-usuarios/cadastro-sucesso/index.tsx
> +        />
![image](https://user-images.githubusercontent.com/40612788/206044693-aa6d6734-230d-4f8a-a989-f3ba362d474b.png)

2022-12-11 00:49 UTC, davigsousa approved these changes

2022-12-11 00:54 UTC, merged